[project]
name = "indic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "datasets>=5.0.1",
    "groq>=1.6.0",
    "huggingface-hub>=1.27.0",
    "numpy>=2.5.2",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
    "torch>=2.13.0",
]
